//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageProgram.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryNote
    {
        public int DeliveryNoteId { get; set; }
        public string DeliveryNoteIndication { get; set; }
        public string DeliveryNoteOrderOrDelivery { get; set; }
        public Nullable<int> DeliveryNoteCount { get; set; }
        public string DeliveryNoteNameOfCompany { get; set; }
        public Nullable<int> Company_id { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
