//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageProgram.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public string InvoiceDesignation { get; set; }
        public string InviceNameOfCompany { get; set; }
        public int InvoiceAmount { get; set; }
        public System.DateTime InvoiceDate { get; set; }
        public System.DateTime InvoiceDateMaturity { get; set; }
        public string InvoiceType { get; set; }
    }
}
