//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorageProgram.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsInStockDelivery
    {
        public int ItemInDeliveryId { get; set; }
        public string ItemInDeliveryName { get; set; }
        public int ItemInDeliveryCount { get; set; }
        public string ItemInDeliveryDescription { get; set; }
        public int ItemInDeliverySellPrice { get; set; }
        public int ItemInDeliveryFromItemInStockId { get; set; }
        public int ItemInDeliveryFromDeliveryNote { get; set; }
        public string ItemInDeliveryOrderOrDelivery { get; set; }
    }
}
